// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDeConteiners.Data;

namespace RegistroDeConteiners.Migrations
{
    [DbContext(typeof(RegistroDeConteinersContext))]
    [Migration("20210115170118_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("RegistroDeConteiners.Models.Conteiner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numerodecntr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Conteiner");
                });

            modelBuilder.Entity("RegistroDeConteiners.Models.Movimentacoes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConteinerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Navio")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipodeMv")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ConteinerID");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("RegistroDeConteiners.Models.Movimentacoes", b =>
                {
                    b.HasOne("RegistroDeConteiners.Models.Conteiner", "Conteiner")
                        .WithMany()
                        .HasForeignKey("ConteinerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conteiner");
                });
#pragma warning restore 612, 618
        }
    }
}
